apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: libapp
spec:
  applicationImage: quay.io/my-repo/my-app:1.0
  service:
    type: ClusterIP
    port: 9443
  expose: false

  volumes:
  - name: certificates
    secret:
      secretName: liberty-cert-secret

  volumeMounts:
  - name: certificates
    mountPath: /etc/wlp/config/certificates
    readOnly: true
  
