kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: libapp
  labels:
    app.kubernetes.io/instance: libapp
    app.kubernetes.io/managed-by: open-liberty-operator
    app.kubernetes.io/name: libapp
spec:
  to:
    kind: Service
    name: libapp
    weight: 100
  port:
    targetPort: 9443-tcp
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
