# BuildConfig for creating the image containing the image signing initializing server. 
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: signature-init-server
  name: signature-init-server
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: signature-init-server:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
  strategy:
    dockerStrategy: {}
    type: Docker
  successfulBuildsHistoryLimit: 5
